version: '3.3'

services:
  chatbot:
    build: .
    ports:
      - '8501:8501'
    environment:
      DB_URI: postgresql+psycopg2://postgres:postgres@db/postgres
      OLLAMA_URI: http://ollama:11434
      OLLAMA_MODEL: $OLLAMA_MODEL
      STREAMLIT_SERVER_MAX_MESSAGE_SIZE: 250
      PYTHONUNBUFFERED: 1
      PYTHONIOENCODING: UTF-8
    networks:
      - external_network
    depends_on:
      - db

  db:
    build: ./db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_NAME=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./dataset:/dataset
    networks:
      - external_network

volumes:
  db:
    driver: local

networks:
  external_network:
    name: my_external_network
    external: true